[package]
edition = "2024"
name = "tls_validate"
version = "0.1.0"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "pemgen"
path = "src/pemgen.rs"

[dependencies]
rcgen = "0.14.4"
reqwest = "0.12.23"
time = "0.3.44"
tokio = "1.47.1"
